name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: nanapokedex
          environment_name: Nanapokedex-env
          region: ap-northeast-1
          version_label: v-${{ github.sha }}
          deployment_package: backend.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
